# Generated by Django 2.1.2 on 2018-12-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_monitor', '0002_monitor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='status_code',
            field=models.CharField(default=200, max_length=100),
            preserve_default=False,
        ),
    ]
