# Generated by Django 2.1.2 on 2018-12-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_monitor', '0004_monitor_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='interval_minutes',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='last_execution',
        ),
    ]
