# Generated by Django 2.1.2 on 2018-12-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_monitor', '0006_monitor_current_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='last_trouble',
            field=models.DateTimeField(null=True),
            preserve_default=False,
        ),
    ]
