# Generated by Django 2.1.2 on 2018-12-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_monitor', '0007_monitor_last_trouble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='current_status_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='last_trouble',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
