# Generated by Django 2.1.2 on 2018-12-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_monitor', '0008_auto_20181216_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='last_execution',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
